Add npm publish to GitHub actions
auth0/jwt-decode pull request #203
Opened 2023-08-25 12:36 UTC by frederikprijck

### Description

Adds support to publish to npm using GitHub actions

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not the default branch

2023-08-25 14:08 UTC, jonkoops requested changes

2023-08-25 14:08 UTC, jonkoops commented on .github/workflows/publish.yml
> +    name: 'NPM'
This should probably be a more human readable string.
```suggestion
    name: Publish to NPM
```

2023-08-25 14:08 UTC, jonkoops commented on .github/workflows/publish.yml
> +          cache: 'npm'
```suggestion
          cache: npm
```

2023-08-25 14:08 UTC, jonkoops commented on .github/workflows/publish.yml
> +        run: npm run build
Is this step required? Would it not be better to handle this in the `prepublishOnly` script?

2023-08-26 12:39 UTC, jonkoops commented on .github/workflows/publish.yml
> +        run: npm run build
Cool, then let's just leave it as is :)

2023-08-29 03:36 UTC, evansims approved these changes

2023-08-29 03:36 UTC, merged